import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`min-h-screen bg-[url('/images/HaloCover.jpg')] bg-cover bg-center`}
      >
        <Providers>{children}</Providers>
        <Script src="https://unpkg.com/typewriter-effect@latest/dist/core.js" />
      </body>
    </html>
  );
}
